# Generated by Django 4.1.1 on 2022-10-23 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='camaras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='sensorhumedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('tiempoderiego', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sensortemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('tempmax', models.IntegerField()),
                ('tempmin', models.IntegerField()),
                ('tempactual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('fecha', models.DateField(null=True)),
                ('localidad', models.CharField(max_length=45)),
                ('camarasid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camaras', to='app.camaras')),
                ('sensorhumedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_humedad', to='app.sensorhumedad')),
                ('sensortemperatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_temperatura', to='app.sensortemperatura')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerocultivos', models.IntegerField()),
                ('cultivos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultivo', to='app.cultivo')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
