# Generated by Django 4.1.2 on 2022-10-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='fecha',
            field=models.DateField(),
        ),
    ]
