# Generated by Django 4.1.2 on 2022-10-24 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cultivo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='camarasid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camaras', to='app.camaras'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='localidad',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='sensorhumedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensor_humedad', to='app.sensorhumedad'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='sensortemperatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensor_temperatura', to='app.sensortemperatura'),
        ),
    ]
