# Generated by Django 4.1.1 on 2022-10-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sensorhumedad_humedadactual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='cultivos',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrador', to='app.administrador'),
        ),
    ]
